set_machine_state:
  fields:
    state:
      required: true
      selector:
        select:
          options:
            - "idle"
            - "sleeping"
            - "espresso"
            - "hotWater"
            - "steam"
            - "flush"
    config_entry_id:
      required: false
      selector:
        config_entry:
          integration: decent_app
